# Generated by Django 4.2.20 on 2025-04-16 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='content',
            field=models.TextField(null=True),
        ),
    ]
